# Generated by Django 5.2.8 on 2025-11-14 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Ragione sociale')),
                ('vat_number', models.CharField(max_length=32, verbose_name='Partita IVA')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='CAP')),
                ('country', models.CharField(default='Italia', max_length=100, verbose_name='Paese')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('default_commission_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentuale di revenue riconosciuta al partner sugli ordini.', max_digits=5, verbose_name='Commissione di default (%)')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partner',
            },
        ),
    ]
