# Generated by Django 5.2.8 on 2025-11-24 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('message', models.TextField(verbose_name='Messaggio')),
                ('url', models.CharField(blank=True, help_text='URL da aprire quando il partner clicca la notifica (es: dettaglio ordine).', max_length=255, verbose_name='Link di destinazione')),
                ('is_read', models.BooleanField(default=False, verbose_name='Letta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='partners.partnerprofile', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Notifica partner',
                'verbose_name_plural': 'Notifiche partner',
                'ordering': ['-created_at'],
            },
        ),
    ]
