# Generated by Django 5.2.8 on 2025-12-15 11:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_partner_commission_rate'),
        ('partners', '0002_partnernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategoryCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentuale di commissione per questa categoria (es. 12.50).', max_digits=5, verbose_name='Commissione categoria (%)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commissions', to='catalog.category', verbose_name='Categoria prodotto')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_commissions', to='partners.partnerprofile', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Commissione per categoria',
                'verbose_name_plural': 'Commissioni per categoria',
                'unique_together': {('partner', 'category')},
            },
        ),
    ]
