# Generated by Django 5.2.8 on 2025-11-14 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Indirizzo fatturazione'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Città fatturazione'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Paese fatturazione'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='CAP fatturazione'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ragione sociale'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vat_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Partita IVA'),
        ),
        migrations.CreateModel(
            name='ClientStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome struttura')),
                ('address', models.CharField(max_length=255, verbose_name='Indirizzo')),
                ('city', models.CharField(max_length=100, verbose_name='Città')),
                ('zip_code', models.CharField(max_length=20, verbose_name='CAP')),
                ('country', models.CharField(default='Italia', max_length=100, verbose_name='Paese')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('is_default_shipping', models.BooleanField(default=False, verbose_name='Usa come indirizzo di spedizione predefinito')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Struttura Cliente',
                'verbose_name_plural': 'Strutture Clienti',
            },
        ),
    ]
