# Generated by Django 5.2.8 on 2025-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pec_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='PEC'),
        ),
        migrations.AddField(
            model_name='user',
            name='sdi_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Codice SDI'),
        ),
    ]
