# Generated by Django 5.2.8 on 2025-12-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_pec_email_user_sdi_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Amministratore'), ('partner', 'Partner'), ('client', 'Cliente'), ('content_manager', 'Content Manager')], default='client', max_length=20),
        ),
    ]
