# Generated by Django 5.2.8 on 2025-11-14 10:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome categoria')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome prodotto/servizio')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Descrizione breve')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione completa')),
                ('is_service', models.BooleanField(default=False, help_text='Spunta se è un servizio (no spedizione fisica).')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prezzo base')),
                ('unit', models.CharField(choices=[('per_kit', 'per kit'), ('per_piece', 'per pezzo'), ('per_night', 'per notte')], default='per_kit', max_length=20, verbose_name='Unità di prezzo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('supplier', models.ForeignKey(blank=True, help_text='Partner che eroga questo prodotto/servizio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='partners.partnerprofile')),
            ],
            options={
                'verbose_name': 'Prodotto/Servizio',
                'verbose_name_plural': 'Prodotti/Servizi',
            },
        ),
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome componente')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('kit', models.ForeignKey(limit_choices_to={'is_service': False}, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Componente kit',
                'verbose_name_plural': 'Componenti kit',
            },
        ),
    ]
