# Generated by Django 5.2.8 on 2025-11-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_main_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantità disponibile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Disponibilità prodotto',
                'verbose_name_plural': 'Disponibilità prodotti',
                'ordering': ['date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
