# Generated by Django 5.2.8 on 2025-12-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='comment',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='productrating',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
