# Generated by Django 5.2.8 on 2025-12-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productrating_comment_productrating_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('approved', 'Approvata'), ('rejected', 'Rifiutata')], db_index=True, default='pending', help_text='Stato della moderazione: in attesa / approvata / rifiutata.', max_length=20),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='True se la recensione è approvata e visibile.'),
        ),
    ]
