# Generated by Django 5.2.8 on 2025-12-05 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productrating_moderation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='moderated_at',
            field=models.DateTimeField(blank=True, help_text="Data/ora dell'ultima moderazione.", null=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text="Utente staff che ha effettuato l'ultima moderazione.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
