# Generated by Django 5.2.8 on 2025-12-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productrating_moderated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='partner_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se valorizzato, questo valore viene usato come commissione per questo prodotto (priorità più alta).', max_digits=5, null=True, verbose_name='Commissione specifica prodotto (%)'),
        ),
    ]
