# Generated by Django 5.2.8 on 2025-11-14 10:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_billing_address_user_billing_city_and_more'),
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('pending_payment', 'In attesa pagamento'), ('paid', 'Pagato'), ('processing', 'In lavorazione'), ('shipped', 'Spedito'), ('completed', 'Completato'), ('cancelled', 'Annullato')], default='pending_payment', max_length=20, verbose_name='Stato ordine')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bonifico bancario'), ('cash_on_delivery', 'Pagamento alla consegna')], default='bank_transfer', max_length=20, verbose_name='Metodo di pagamento')),
                ('payment_reference', models.CharField(blank=True, max_length=255, verbose_name='Riferimento pagamento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotale')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Spese di spedizione')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Totale ordine')),
                ('notes', models.TextField(blank=True, verbose_name='Note del cliente')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Note amministratore')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name="Fattura (caricata dall'amministratore)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(help_text='Struttura a cui è destinata la merce/servizio.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.clientstructure')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totale riga')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('partner', models.ForeignKey(help_text='Partner al quale è assegnato questo articolo.', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='partners.partnerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': "Riga d'ordine",
                'verbose_name_plural': "Righe d'ordine",
            },
        ),
    ]
