# Generated by Django 5.2.8 on 2025-11-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='partner_status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('accepted', 'Accettato'), ('in_progress', 'In lavorazione'), ('shipped', 'Spedito'), ('completed', 'Completato'), ('rejected', 'Rifiutato')], default='pending', max_length=20, verbose_name='Stato (partner)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner al quale è assegnato questo articolo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='partners.partnerprofile'),
        ),
    ]
