# Generated by Django 5.2.8 on 2025-11-24 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_partner_status_alter_orderitem_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'In attesa'), ('accepted', 'Accettato'), ('in_progress', 'In lavorazione'), ('shipped', 'Spedito'), ('completed', 'Completato'), ('rejected', 'Rifiutato')], help_text='Stato partner prima della modifica (può essere nullo se è il primo stato).', max_length=20, null=True, verbose_name='Stato precedente')),
                ('new_status', models.CharField(choices=[('pending', 'In attesa'), ('accepted', 'Accettato'), ('in_progress', 'In lavorazione'), ('shipped', 'Spedito'), ('completed', 'Completato'), ('rejected', 'Rifiutato')], max_length=20, verbose_name='Nuovo stato')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data modifica')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitem_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.orderitem', verbose_name="Riga d'ordine")),
            ],
            options={
                'verbose_name': "Log stato riga d'ordine",
                'verbose_name_plural': "Log stati righe d'ordine",
                'ordering': ['-changed_at'],
            },
        ),
    ]
