# Generated by Django 5.2.8 on 2025-11-25 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitemstatuslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('client', 'Cliente'), ('partner', 'Partner'), ('admin', 'Admin')], max_length=10, verbose_name='Ruolo mittente')),
                ('message', models.TextField(verbose_name='Messaggio')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='order_messages/', verbose_name='Allegato')),
                ('is_read_by_client', models.BooleanField(default=False, verbose_name='Letto dal cliente')),
                ('is_read_by_partner', models.BooleanField(default=False, verbose_name='Letto dal partner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order', verbose_name='Ordine')),
                ('order_item', models.ForeignKey(blank=True, help_text='Opzionale: se il messaggio si riferisce a una riga specifica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.orderitem', verbose_name="Riga d'ordine")),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_order_messages', to=settings.AUTH_USER_MODEL, verbose_name='Mittente')),
            ],
            options={
                'verbose_name': 'Messaggio ordine',
                'verbose_name_plural': 'Messaggi ordine',
                'ordering': ['created_at'],
            },
        ),
    ]
