# Generated by Django 5.2.8 on 2025-11-25 12:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordermessage'),
        ('partners', '0002_partnernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Importo commissione'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentuale sul totale riga (es. 10 = 10%).', max_digits=5, verbose_name='Percentuale commissione'),
        ),
        migrations.CreateModel(
            name='PartnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Periodo da')),
                ('period_end', models.DateField(verbose_name='Periodo a')),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Totale commissioni')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('confirmed', 'Confermato'), ('paid', 'Pagato')], default='draft', max_length=20, verbose_name='Stato pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagato il')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='partners.partnerprofile', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Pagamento partner',
                'verbose_name_plural': 'Pagamenti partner',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
    ]
