# Generated by Django 5.2.8 on 2025-11-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_liquidated',
            field=models.BooleanField(default=False, help_text='Indica se la commissione di questa riga è già stata liquidata tramite payout.', verbose_name='Liquidata'),
        ),
    ]
