# Generated by Django 5.2.8 on 2025-11-28 09:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_is_liquidated'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='partner_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Importo partner'),
        ),
    ]
