# Generated by Django 5.2.8 on 2025-12-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_partner_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpayout',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='Allega la ricevuta del bonifico o documento contabile.', null=True, upload_to='payout_receipts/', verbose_name='Ricevuta di pagamento'),
        ),
    ]
