# Generated by Django 5.2.8 on 2025-12-09 18:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_partnerpayout_payment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpayout',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Totale da liquidare al partner'),
        ),
    ]
