# Generated by Django 5.2.8 on 2025-12-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_partnerpayout_total_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
