# Generated by Django 5.2.8 on 2025-12-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_review_invite_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.partnerpayout'),
        ),
    ]
